version: '3.8'

services:
  flask:
    build: ./flask
    container_name: flask 
    restart: always
    command: gunicorn --bind :5000 'manage:create_app()'
    expose:
      - 5000
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask

  redis:
    image: redis:latest
    container_name: redis
    expose: 
      -  6379
    ports: 
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]